### ISSUE TITLE
Support Multi-tab Dotlan Use

### ISSUE THREAD

**Issue by IcyMidnight** [ArtificialQualia/DOTLAN-Radar-Chrome-Extension#2]
This plugin is great if you only have one Dotlan tab open but if you try to use another Dotlan tab, say to look at the map one region over, the plugin forces you out of whichever view you're in and dumps you into the tracking view no matter what. Worse, if you already have another map tab open, you can end up losing your state because you're pulled out of whatever you're already doing, say planning a capital jump route.

It would be really nice to have tracking active on a per-tab basis instead of globally across the whole brower. It would be even better if navigating to a new place in Dotlan automatically disabled tracking until it was manually turned back on.

**Comment by ArtificialQualia** [comment]
This has been added, the update to the chrome extension is pending a review by Google.

**Comment by ArtificialQualia** [comment]
Update has been released, let me know if you have any issues.

**Comment by IcyMidnight** [comment]
That's much nicer. Thanks!
