### ISSUE TITLE
Multi-tab tracking screws usage

### ISSUE THREAD

**Issue by TyrHeimdalEVE** [ArtificialQualia/DOTLAN-Radar-Chrome-Extension#3]
Hi!

First I'd like to say thanks for this wonderful Extension (only wish would be a Firefox version!). However the usefulness have diminished due to a recent update.

In #2 / d5cf476 you added Multi-tab support, which is great in theory. But it overwrites the selected Map Info Layer URI fragments.

For example if I'm in 1DQ1-A and select NPC, I'll get the URL: https://evemaps.dotlan.net/map/Delve/1DQ1-A#npc
Now if I jump into another system, it'll be replaced by for example: https://evemaps.dotlan.net/system/8WA-Z6#?tracking

Was this really intended...?

References:
https://tools.ietf.org/html/rfc3986#section-3.5

**Comment by ArtificialQualia** [comment]
Nope, this was not intended.  I'll look into fixing it.

**Comment by TyrHeimdalEVE** [comment]
Appreciate the swift response!

Since the browser will use the entire URI fragment and I'm not aware of any good ways to split it, you *could* call this as for example: `https://evemaps.dotlan.net/map/Delve/1DQ1-A?tracking#npc`

I'd suggest you make it more unique though, since it would be sent to the webserver as a parameter in the request. Not certain if any map related stuff on Dotlan uses `?` as a splitter, but can't remember ever seeing anything else than `/` and `,` for splitting on their site.

As you are using url.indexOf in your if statement to choose radarTrackingEnabled = true/false, this would probably still work just fine if you appended whatever is in the fragment after your `?tracking`.

**Comment by ArtificialQualia** [comment]
Good suggestion, I had already started adding it that way when you replied!

Ideally I wouldn't store state in the URL at all, but it is quick and easy in this case where I don't want state stored across tabs and it needs to preserve state across pages.  There are better ways to do this, but none as simple as chucking it in the query string.  If this extension ever got more advanced, or dotlan changes significantly, it may be worth addressing.

I appreciate your detailed bug report.  The new version (v1.1.1) is awating approval in the Chrome store, it is usually available in about 1 day barring any approval issues.

Let me know if you encounter any other bugs.  Thanks!

**Comment by TyrHeimdalEVE** [comment]
Yeah that's absolutely understandable. I'd probably do the same myself for a smaller hobby project. There's no right and wrong when a "dirty hack" does the trick. ;)

Thanks a lot for fixing this in record time! It's been bugging me ever since I updated it. For sure I will come poke you again or even submit a PR if I find something that could be improved/fixed.

Have a nice weekend!
