### ISSUE TITLE
Changed to other language.

### ISSUE THREAD

**Issue by Beeeeeeeens** [ArtificialQualia/DOTLAN-Radar-Chrome-Extension#4]
When I start tracking, the system name is in a language other than English.

Maybe change it this way and see how it goes.

DOTLAN-Radar-Chrome-Extension/app/scripts/tracker.js
before
`      url: 'https://esi.evetech.net/latest/universe/regions/'+response.data['region_id']+'/'`
after
`      url: 'https://esi.evetech.net/latest/universe/regions/'+response.data['region_id']+'/?language=en'`

**Comment by ArtificialQualia** [comment]
Thanks for the heads up, I didn't realize ESI responded in different languages for other users.  I'll look at updating this.

**Comment by ArtificialQualia** [comment]
Sorry I forgot about this issue!  This change has been included in the newest v1.2.0 release
