### ISSUE TITLE
Waypoint broken

### ISSUE THREAD

**Issue by Stridsflygplan** [ArtificialQualia/DOTLAN-Radar-Chrome-Extension#5]
In the latest patch setting waypoints stopped working with ESI Radar.

**Comment by ArtificialQualia** [comment]
Thanks for the heads up.
CCP has completely removed a public API endpoint this extension depended on with absolutely no warning or notice.

I can look into working around that, but it will take me some time as I haven't played EVE in a number of years.

**Comment by Stridsflygplan** [comment]
Hi, I am happy you are still around since I absolutely love the app and make all my friends use it.

Yes we had a similar thing happen in corp, we have a tech guy to that run into the same problem when this endpoint was removed from the API/ESI.

here is the convo we had (I am no tech guy so I hope any of this info might be of use):



  1.
[DLVRN] Larynx Austrene — 12/07/2022
https://esi.evetech.net/ui/#/Search https://web.archive.org/web/20220706080854/https://esi.evetech.net/ui/#/Search/ yo, am I living under a rock or is CCP just randomly removing API enpoints?
  2.
[https://cdn.discordapp.com/avatars/139505889072644096/6fb7b1b9772ba5cc743c68e3a2b2e5a7.webp?size=80]
[DLVRN] Strids — 12/07/2022
wasnt the api shut down and replaced by the ESI years ago by now?
  3.
[21:14]
oh that is the esi
  4.
[21:14]
dude I need to shut up more. I have no clue
  5.
[https://cdn.discordapp.com/avatars/242164531151765505/79ce3fe44a40d28b92afb7652e919dfe.webp?size=80]
[DLVRN] Larynx Austrene — 12/07/2022
Me neither
  6.
[21:16]
But it looks like the endpoint I was using just disappeared since last week
  7.
[21:16]
Grrr CCP
  8.
[https://cdn.discordapp.com/avatars/139505889072644096/6fb7b1b9772ba5cc743c68e3a2b2e5a7.webp?size=80]
[DLVRN] Strids — 12/07/2022
ask around on the eve slack or steve ronuken maybe
  9.
***@***.*** Larynx Austrene
https://esi.evetech.net/ui/#/Search  https://web.archive.org/web/20220706080854/https://esi.evetech.net/ui/#/Search/ yo, am I living under a rock or is CCP just randomly removing API enpoints?
[https://cdn.discordapp.com/avatars/165224606087643136/045590e376c653c72af0c110095e54f6.webp?size=80]
[DLVRN] Jesse Swale — 12/07/2022
I had the same issue a few months ago with the API /corporations/{corporation_id}/wallets/{division}/transactions/. It came back after 2 days or so
  10.
[21:29]
Unless they really just removed it, which should be worth a sentence or two in some patch notes / dev blogs or whatever.
  11.
[https://cdn.discordapp.com/avatars/242164531151765505/79ce3fe44a40d28b92afb7652e919dfe.webp?size=80]
[DLVRN] Larynx Austrene — 12/07/2022
I will just wait around a bit then
  12.
[https://cdn.discordapp.com/avatars/165224606087643136/045590e376c653c72af0c110095e54f6.webp?size=80]
[DLVRN] Jesse Swale — 12/07/2022
https://github.com/esi/esi-issues/issues/1319#issue-1222084645 @[DLVRN] Larynx Austrene. Similar problem, from 2 months ago. I bet its up again in a few days
  13.
[https://cdn.discordapp.com/avatars/178140778831413248/b41ab772d03c8f4a4caad35bc58a0165.webp?size=80]
[DLVRN] howling wind — 12/07/2022
they removed a search endpoint and replaced it with an authenticated one
  14.
[21:42]
<https://i.imgur.com/oTmeLHc.png>
https://i.imgur.com/oTmeLHc.png[https://i.imgur.com/oTmeLHc.png]

  15.
[https://cdn.discordapp.com/avatars/242164531151765505/79ce3fe44a40d28b92afb7652e919dfe.webp?size=80]
[DLVRN] Larynx Austrene — 12/07/2022
lol
  16.
[21:45]
Fixing stability issues by making it harder for users to use
  17.
[21:47]
I hope someone makes one that is unauthed and just provides their auth xD
  18.

  19.
[https://cdn.discordapp.com/avatars/242164531151765505/79ce3fe44a40d28b92afb7652e919dfe.webp?size=80]
[DLVRN] Larynx Austrene — 12/07/2022
Hmm. what do I do? a) Figure out how to deal with the whole authentication flow and somehow get a token, then figure out how to ship it to people without making it more complicated for them to set up. b) Just querry every single corp / character / alliance and store in a dictionary, do it again every time a new instance gets set up.
  20.
[https://cdn.discordapp.com/avatars/217656563156910081/c1a6fc5e93dfc09e42d06b89b997ed27.webp?size=80]
[DLVRN] T'rahk Rokym — 12/07/2022
the auth flow isn't super hard to work arround but it's a pain to setup at first, but in which case do you need all alliance names?
  21.
[https://cdn.discordapp.com/avatars/242164531151765505/79ce3fe44a40d28b92afb7652e919dfe.webp?size=80]
[DLVRN] Larynx Austrene — 12/07/2022
It's just for the killbucket discord bot
  22.
[23:38]
I just want to get Ids from names (edited)
  23.
[23:39]
And there are no state holding elements in the project so far (edited)
  24.
[https://cdn.discordapp.com/avatars/217656563156910081/c1a6fc5e93dfc09e42d06b89b997ed27.webp?size=80]
[DLVRN] T'rahk Rokym — 12/07/2022
just use /universe/names/
  25.
[23:40]
that would be the easy solution imo
  26.
[23:41]
wait not /universe/ids/
  27.
[23:41]
I remember it as not being an amazing endpoint to work arround but it works
  28.
[https://cdn.discordapp.com/avatars/242164531151765505/79ce3fe44a40d28b92afb7652e919dfe.webp?size=80]
[DLVRN] Larynx Austrene — 12/07/2022
That looks good
  29.
[23:42]
God bless
  30.
[23:43]
I was reeing pretty hard ngl
  31.
[https://cdn.discordapp.com/avatars/217656563156910081/c1a6fc5e93dfc09e42d06b89b997ed27.webp?size=80]
[DLVRN] T'rahk Rokym — 12/07/2022
[:PepeLaugh~1:]
  32.
[23:43]
CCP moment

Hope that helps. If you need help I can try to do my best and get my corpies to help ya.

o7
________________________________

**Comment by ArtificialQualia** [comment]
Thanks for the extra info.  I have put in a fix that works locally and have submitted the update to the extension as v1.2.0.  It can take Chrome some time to approve extension updates, so I'll leave this issue open until the new update is approved by Chrome and I can get some confirmation that the fix is working properly.

**Comment by Stridsflygplan** [comment]
Thanks for the update. o7

**Comment by ArtificialQualia** [comment]
@Stridsflygplan the update is finally live, can you confirm that setting destinations/waypoints is now working for you?

**Comment by Stridsflygplan** [comment]
@ArtificialQualia I tried it now and both destinations/waypoints are working.

**Comment by ArtificialQualia** [comment]
Great!  Appreciate you following up.  Closing this issue.
